=== miguelbarrosv/JEMS/XML/DTD_Jornada.dtd
<!ELEMENT jornadas (jornada+)>
<!ELEMENT jornada (partidos,fecha)>
	<!ATTLIST jornada cod #CDATA #REQUIRED>
	<!ATTLIST jornada fecha #CDATA #REQUIRED>
	<!ELEMENT partidos (partido+)>
		<!ELEMENT partido (equipoA, equipoB, puntuacionA,puntuacionB)>
			<!ATTLIST partido cod #CDATA #REQUIRED>
			<!ELEMENT equipoA (#PCDATA)>
			<!ELEMENT equipoB (#PCDATA)>
			<!ELEMENT puntuacionA (#PCDATA)>
			<!ELEMENT puntuacionB (#PCDATA)>

=== miguelbarrosv/JEMS/XML/XMLjornadaBASE.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE DTD_Jornada SYSTEM "DTD_Jornada.dtd">
	<jornadas>
		<jornada cod="02" fecha="07/05/2019">
			<partidos>
				<partido cod="01">
					<equipoA></equipoA>				
					<equipoB></equipoB>
					<puntuacionA>0</puntuacionB>
					<puntuacionB>0</puntuacionB>
				</partido>
				<partido cod="02">
					<equipoA></equipoA>				
					<equipoB></equipoB>
					<puntuacionA>0</puntuacionB>
					<puntuacionB>0</puntuacionB>
				</partido>
				<partido cod="03">
					<equipoA></equipoA>				
					<equipoB></equipoB>
					<puntuacionA>0</puntuacionB>
					<puntuacionB>0</puntuacionB>
				</partido>
			</partidos>
		</jornada>		
		<jornada cod="01" fecha="06/05/2019">
			<partidos>
				<partido cod="01">
					<equipoA></equipoA>				
					<equipoB></equipoB>
					<puntuacionA>0</puntuacionB>
					<puntuacionB>0</puntuacionB>
				</partido>
				<partido cod="02">
					<equipoA></equipoA>				
					<equipoB></equipoB>
					<puntuacionA>0</puntuacionB>
					<puntuacionB>0</puntuacionB>
				</partido>
				<partido cod="03">
					<equipoA></equipoA>				
					<equipoB></equipoB>
					<puntuacionA>0</puntuacionB>
					<puntuacionB>0</puntuacionB>
				</partido>
			</partidos>
		</jornada>
	</jornadas>
